//created on: 10.12.2016
package priorules;

import edu.thi.models.Bestellungen;
//declare any global variables here

rule "SelectPriority1"

    when
       $s : Bestellungen(name == "Paracetamol")
    then
       $s.setPriority(1);
       $s.setName("");
       update($s);
end

rule "SelectPriority2"

    when
       $s : Bestellungen(name == "Ibuprofen")
    then
       $s.setPriority(2);
       $s.setName("");
       update($s);
end
